apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- namespace.yaml
- service.yaml
- ingress.yaml
- pvc.yaml
commonLabels:
  app.kubernetes.io/name: pospai
namespace: app-pospai
